// Generated by gencpp from file pr2_robot/GraspResponse.msg
// DO NOT EDIT!


#ifndef PR2_ROBOT_MESSAGE_GRASPRESPONSE_H
#define PR2_ROBOT_MESSAGE_GRASPRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace pr2_robot
{
template <class ContainerAllocator>
struct GraspResponse_
{
  typedef GraspResponse_<ContainerAllocator> Type;

  GraspResponse_()
    : grasp_pose()  {
    }
  GraspResponse_(const ContainerAllocator& _alloc)
    : grasp_pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _grasp_pose_type;
  _grasp_pose_type grasp_pose;




  typedef boost::shared_ptr< ::pr2_robot::GraspResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pr2_robot::GraspResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GraspResponse_

typedef ::pr2_robot::GraspResponse_<std::allocator<void> > GraspResponse;

typedef boost::shared_ptr< ::pr2_robot::GraspResponse > GraspResponsePtr;
typedef boost::shared_ptr< ::pr2_robot::GraspResponse const> GraspResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pr2_robot::GraspResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pr2_robot::GraspResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pr2_robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pr2_robot::GraspResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pr2_robot::GraspResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pr2_robot::GraspResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pr2_robot::GraspResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr2_robot::GraspResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr2_robot::GraspResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pr2_robot::GraspResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "306dcb5b004c7872f94310686b0d0609";
  }

  static const char* value(const ::pr2_robot::GraspResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x306dcb5b004c7872ULL;
  static const uint64_t static_value2 = 0xf94310686b0d0609ULL;
};

template<class ContainerAllocator>
struct DataType< ::pr2_robot::GraspResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pr2_robot/GraspResponse";
  }

  static const char* value(const ::pr2_robot::GraspResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pr2_robot::GraspResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
geometry_msgs/Pose grasp_pose\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::pr2_robot::GraspResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pr2_robot::GraspResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.grasp_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GraspResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pr2_robot::GraspResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pr2_robot::GraspResponse_<ContainerAllocator>& v)
  {
    s << indent << "grasp_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.grasp_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PR2_ROBOT_MESSAGE_GRASPRESPONSE_H
