// Generated by gencpp from file pr2_robot/GraspRequest.msg
// DO NOT EDIT!


#ifndef PR2_ROBOT_MESSAGE_GRASPREQUEST_H
#define PR2_ROBOT_MESSAGE_GRASPREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>
#include <std_msgs/Int32.h>

namespace pr2_robot
{
template <class ContainerAllocator>
struct GraspRequest_
{
  typedef GraspRequest_<ContainerAllocator> Type;

  GraspRequest_()
    : object_name()
    , test_scene_num()  {
    }
  GraspRequest_(const ContainerAllocator& _alloc)
    : object_name(_alloc)
    , test_scene_num(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _object_name_type;
  _object_name_type object_name;

   typedef  ::std_msgs::Int32_<ContainerAllocator>  _test_scene_num_type;
  _test_scene_num_type test_scene_num;




  typedef boost::shared_ptr< ::pr2_robot::GraspRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pr2_robot::GraspRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GraspRequest_

typedef ::pr2_robot::GraspRequest_<std::allocator<void> > GraspRequest;

typedef boost::shared_ptr< ::pr2_robot::GraspRequest > GraspRequestPtr;
typedef boost::shared_ptr< ::pr2_robot::GraspRequest const> GraspRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pr2_robot::GraspRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pr2_robot::GraspRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pr2_robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pr2_robot::GraspRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pr2_robot::GraspRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pr2_robot::GraspRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pr2_robot::GraspRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr2_robot::GraspRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr2_robot::GraspRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pr2_robot::GraspRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "458f028c2a9a12053f64932c127d35f4";
  }

  static const char* value(const ::pr2_robot::GraspRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x458f028c2a9a1205ULL;
  static const uint64_t static_value2 = 0x3f64932c127d35f4ULL;
};

template<class ContainerAllocator>
struct DataType< ::pr2_robot::GraspRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pr2_robot/GraspRequest";
  }

  static const char* value(const ::pr2_robot::GraspRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pr2_robot::GraspRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
std_msgs/String object_name\n\
std_msgs/Int32 test_scene_num\n\
\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
\n\
================================================================================\n\
MSG: std_msgs/Int32\n\
int32 data\n\
";
  }

  static const char* value(const ::pr2_robot::GraspRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pr2_robot::GraspRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object_name);
      stream.next(m.test_scene_num);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GraspRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pr2_robot::GraspRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pr2_robot::GraspRequest_<ContainerAllocator>& v)
  {
    s << indent << "object_name: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.object_name);
    s << indent << "test_scene_num: ";
    s << std::endl;
    Printer< ::std_msgs::Int32_<ContainerAllocator> >::stream(s, indent + "  ", v.test_scene_num);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PR2_ROBOT_MESSAGE_GRASPREQUEST_H
