// Generated by gencpp from file pr2_robot/Grasp.msg
// DO NOT EDIT!


#ifndef PR2_ROBOT_MESSAGE_GRASP_H
#define PR2_ROBOT_MESSAGE_GRASP_H

#include <ros/service_traits.h>


#include <pr2_robot/GraspRequest.h>
#include <pr2_robot/GraspResponse.h>


namespace pr2_robot
{

struct Grasp
{

typedef GraspRequest Request;
typedef GraspResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Grasp
} // namespace pr2_robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pr2_robot::Grasp > {
  static const char* value()
  {
    return "982194e190e8ba0c9866716771b038e9";
  }

  static const char* value(const ::pr2_robot::Grasp&) { return value(); }
};

template<>
struct DataType< ::pr2_robot::Grasp > {
  static const char* value()
  {
    return "pr2_robot/Grasp";
  }

  static const char* value(const ::pr2_robot::Grasp&) { return value(); }
};


// service_traits::MD5Sum< ::pr2_robot::GraspRequest> should match 
// service_traits::MD5Sum< ::pr2_robot::Grasp > 
template<>
struct MD5Sum< ::pr2_robot::GraspRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pr2_robot::Grasp >::value();
  }
  static const char* value(const ::pr2_robot::GraspRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pr2_robot::GraspRequest> should match 
// service_traits::DataType< ::pr2_robot::Grasp > 
template<>
struct DataType< ::pr2_robot::GraspRequest>
{
  static const char* value()
  {
    return DataType< ::pr2_robot::Grasp >::value();
  }
  static const char* value(const ::pr2_robot::GraspRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pr2_robot::GraspResponse> should match 
// service_traits::MD5Sum< ::pr2_robot::Grasp > 
template<>
struct MD5Sum< ::pr2_robot::GraspResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pr2_robot::Grasp >::value();
  }
  static const char* value(const ::pr2_robot::GraspResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pr2_robot::GraspResponse> should match 
// service_traits::DataType< ::pr2_robot::Grasp > 
template<>
struct DataType< ::pr2_robot::GraspResponse>
{
  static const char* value()
  {
    return DataType< ::pr2_robot::Grasp >::value();
  }
  static const char* value(const ::pr2_robot::GraspResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PR2_ROBOT_MESSAGE_GRASP_H
