// Generated by gencpp from file pr2_robot/PickPlaceResponse.msg
// DO NOT EDIT!


#ifndef PR2_ROBOT_MESSAGE_PICKPLACERESPONSE_H
#define PR2_ROBOT_MESSAGE_PICKPLACERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pr2_robot
{
template <class ContainerAllocator>
struct PickPlaceResponse_
{
  typedef PickPlaceResponse_<ContainerAllocator> Type;

  PickPlaceResponse_()
    : success(false)  {
    }
  PickPlaceResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;




  typedef boost::shared_ptr< ::pr2_robot::PickPlaceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pr2_robot::PickPlaceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PickPlaceResponse_

typedef ::pr2_robot::PickPlaceResponse_<std::allocator<void> > PickPlaceResponse;

typedef boost::shared_ptr< ::pr2_robot::PickPlaceResponse > PickPlaceResponsePtr;
typedef boost::shared_ptr< ::pr2_robot::PickPlaceResponse const> PickPlaceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pr2_robot::PickPlaceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pr2_robot::PickPlaceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pr2_robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pr2_robot::PickPlaceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pr2_robot::PickPlaceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pr2_robot::PickPlaceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pr2_robot::PickPlaceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr2_robot::PickPlaceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr2_robot::PickPlaceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pr2_robot::PickPlaceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::pr2_robot::PickPlaceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::pr2_robot::PickPlaceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pr2_robot/PickPlaceResponse";
  }

  static const char* value(const ::pr2_robot::PickPlaceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pr2_robot::PickPlaceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
bool success\n\
\n\
";
  }

  static const char* value(const ::pr2_robot::PickPlaceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pr2_robot::PickPlaceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PickPlaceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pr2_robot::PickPlaceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pr2_robot::PickPlaceResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PR2_ROBOT_MESSAGE_PICKPLACERESPONSE_H
