// Generated by gencpp from file sensor_stick/GetNormals.msg
// DO NOT EDIT!


#ifndef SENSOR_STICK_MESSAGE_GETNORMALS_H
#define SENSOR_STICK_MESSAGE_GETNORMALS_H

#include <ros/service_traits.h>


#include <sensor_stick/GetNormalsRequest.h>
#include <sensor_stick/GetNormalsResponse.h>


namespace sensor_stick
{

struct GetNormals
{

typedef GetNormalsRequest Request;
typedef GetNormalsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetNormals
} // namespace sensor_stick


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sensor_stick::GetNormals > {
  static const char* value()
  {
    return "0a9bb8a1d7550c14c769843382adf4ac";
  }

  static const char* value(const ::sensor_stick::GetNormals&) { return value(); }
};

template<>
struct DataType< ::sensor_stick::GetNormals > {
  static const char* value()
  {
    return "sensor_stick/GetNormals";
  }

  static const char* value(const ::sensor_stick::GetNormals&) { return value(); }
};


// service_traits::MD5Sum< ::sensor_stick::GetNormalsRequest> should match 
// service_traits::MD5Sum< ::sensor_stick::GetNormals > 
template<>
struct MD5Sum< ::sensor_stick::GetNormalsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sensor_stick::GetNormals >::value();
  }
  static const char* value(const ::sensor_stick::GetNormalsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensor_stick::GetNormalsRequest> should match 
// service_traits::DataType< ::sensor_stick::GetNormals > 
template<>
struct DataType< ::sensor_stick::GetNormalsRequest>
{
  static const char* value()
  {
    return DataType< ::sensor_stick::GetNormals >::value();
  }
  static const char* value(const ::sensor_stick::GetNormalsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sensor_stick::GetNormalsResponse> should match 
// service_traits::MD5Sum< ::sensor_stick::GetNormals > 
template<>
struct MD5Sum< ::sensor_stick::GetNormalsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sensor_stick::GetNormals >::value();
  }
  static const char* value(const ::sensor_stick::GetNormalsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensor_stick::GetNormalsResponse> should match 
// service_traits::DataType< ::sensor_stick::GetNormals > 
template<>
struct DataType< ::sensor_stick::GetNormalsResponse>
{
  static const char* value()
  {
    return DataType< ::sensor_stick::GetNormals >::value();
  }
  static const char* value(const ::sensor_stick::GetNormalsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SENSOR_STICK_MESSAGE_GETNORMALS_H
